### ISSUE TITLE
Progrès de type ET ou OU

### ISSUE THREAD

**Issue by Chucky2401** [Chucky2401/Minecraft-Advancements#12]
Pour réaliser les progrès il y a des conditions.
Certains progrès une condition suffit (ex: *Tué un mob*), d'autres il faut faire toutes les conditions (ex: *Tués tous les mobs*).

**Comment by Chucky2401** [comment]
Avec l'aide d'Olchaldir, j'ai trouvé comment faire pour savoir si le progrès et de type OU (une condition requise seulement) ou de type ET (toutes les conditions requises).
A mettre en place dans le tableau.

**Comment by Chucky2401** [comment]
Dans le tableau, je propose une colonne "Type".
Dans cette colonne, je mets "ET" pour toutes les conditions ou "OU" pour une condition.

Qu'en pensez-vous ?
**Je suis ouvert à d'autres idées !**

**Comment by LaoxMinecraft** [comment]
Il est possible de mettre un code couleur ? du genre 'rouge' les obligatoires (les ET), 'verte' les réalisée et une autre couleur pour les 'optionel' (les OU). ca peut étre plus visuel que des ET/OU ?

**Comment by Olchaldir** [comment]
bonne idée de laox, un code couleur si c'est techniquement faisable

**Comment by Chucky2401** [comment]
@LaoxMinecraft @Olchaldir oui le code couleur c'est bon.
Sauf, qu'avec des tests j'arrive à un problème...

Ce que j'avais trouvé pour ET ou OU qui fonctionnait partout, à des exceptions pour Blaze And Cave...

Faut que je revois tout ça...

**Comment by Chucky2401** [comment]
Voici des exemples de ce que ça donne

Progrès non fait de type "OU"
![Imgur](https://i.imgur.com/4lDvXnYl.png)

Progrès non fait de type "ET"
![Imgur](https://i.imgur.com/8UenyvHl.png)

Progrès fait
![Imgur](https://i.imgur.com/ywnjCBQl.png)

**Comment by Chucky2401** [comment]
Et pour filtrer

![Imgur](https://i.imgur.com/TA02tp0l.png)

**Comment by Olchaldir** [comment]
nice ça semble prometteur

**Comment by Chucky2401** [comment]
Je pars la dessus.

Je clos, si besoin plus tard, en rouvrira un ticket 😉
