### ISSUE TITLE
Les Progrès Milestones et cie

### ISSUE THREAD

**Issue by Olchaldir** [Chucky2401/Minecraft-Advancements#14]
Il y a des progrès qui sont lourds à l'affichage et pas utile dans la poursuite de les obtenir car ce sont les progrès validant qu'ont a fait tous les progrès d'une série comme ceux qui s'appelle milestone dans bac... 

peut-être un filtre pour masquer ces progrès ?

**Comment by Chucky2401** [comment]
Pour moi ça revient à utiliser le masquage de progrès : https://github.com/Chucky2401/Minecraft-Advancements/issues/3

**Comment by Chucky2401** [comment]
En fait, il faudrait ajouter une options pour supprimer les *statistiques* du *Blaze and Cave*

**Comment by Chucky2401** [comment]
Deux options supplémentaires pour les masquer (Milestones et Statistics).
Activer par défaut, donc traiter par le programme. A décocher pour désactiver et ne pas afficher.
