### ISSUE TITLE
Install System error first launch

### ISSUE THREAD

**Issue by Olchaldir** [Chucky2401/Minecraft-Advancements#2]
libgcc_s_dw2-1.dll missing after install during first launch (windows 10 - 1909)

**Comment by Chucky2401** [comment]
Le dépôt distant à été mis à jour.
J'avais oublié de mettre des dll nécessaires 😅.

Je clôture

**Comment by Chucky2401** [comment]
Pour ceux qui auraient le problème avec la version 0.1.1-Bêta, désinstaller l'application et réinstaller là 😉
