### ISSUE TITLE
Réglages

### ISSUE THREAD

**Issue by Chucky2401** [Chucky2401/Minecraft-Advancements#7]
Ajout d'une fenêtres de paramètres pour gérer entre autre le choix de sauvegarder les saisis ou pas.

**Comment by Chucky2401** [comment]
Ajout de la classe et de la fenêtre

![Settings](https://i.imgur.com/NhVQ5Zcm.png)

**Comment by Olchaldir** [comment]
je le mettrai pas en option perso, pour mon usage je reviens quasi toujours sur les mêmes, donc mémoire du chemin précédent par défaut et si j'ai besoin j'irai chercher ailleurs, mais c'est peut-être plus simple en option ?

**Comment by Chucky2401** [comment]
Oui, pour moi côté code ce sera plus facile si c'est une option.
Et je vois le côté ça laisse le choix à l'utilisateur, et si quelqu'un la veut, suffit de l'activer une fois et on l'oublie 😉
